# Generated by Django 4.2.27 on 2025-12-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Apelido')),
                ('slug', models.SlugField(help_text='Usado na URL', max_length=120, unique=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Piloto')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('is_active', models.BooleanField(default=False, verbose_name='Temporada Ativa?')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Usado na URL', max_length=120, unique=True)),
                ('primary_color', models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Cor Secundária')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('date', models.DateField(verbose_name='Data')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Local')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='championship.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['season', 'order'],
                'unique_together': {('season', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DriverTeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Carro')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='championship.driver', verbose_name='Piloto')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_teams', to='championship.season', verbose_name='Temporada')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_drivers', to='championship.team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('season', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Posição')),
                ('fastest_lap', models.BooleanField(default=False, verbose_name='Volta + Rápida?')),
                ('points', models.PositiveIntegerField(default=0, editable=False, verbose_name='Pontos')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='championship.driverteamseason', verbose_name='Piloto/Equipe')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='championship.round', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['position'],
                'unique_together': {('round', 'position')},
            },
        ),
    ]
