# Generated by Django 4.2.30 on 2026-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverteamseason',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Convidados consomem pontos na etapa, mas NÃO aparecem no Ranking Geral.', verbose_name='Piloto Convidado?'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='has_penalty',
            field=models.BooleanField(default=False, verbose_name='Sofreu Punição?'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='penalty_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo da Punição'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Concluído'), ('DNF', 'Não Concluiu (DNF)'), ('DNS', 'Faltou (DNS)')], default='COMPLETED', max_length=10, verbose_name='Status da Prova'),
        ),
    ]
